# Generated by Django 2.2.10 on 2020-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_auto_20200218_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='subject_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
