# Generated by Django 2.2.10 on 2020-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0004_auto_20200219_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='body_html_template',
            field=models.TextField(blank=True, default='<br /><br /><p style="text-align:center;font-size:small;">Click <a href="https://{{ unsubscribe }}">here</a> to unsubscribe from future emails.</p>', help_text='You will have settings and user in the context.', null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='from_email',
            field=models.EmailField(blank=True, default='admin@robertnclayton.net', help_text='Set a custom from email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='from_email_name',
            field=models.CharField(blank=True, default='Administrator', help_text='Set a name for a custom from email.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='reply_to',
            field=models.EmailField(blank=True, default='admin@robertnclayton.net', help_text='Set a custom reply-to email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='subject_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
