# Generated by Django 2.2.10 on 2020-02-23 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0005_auto_20200223_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentdrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_drips', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
